package com.aidb.aidb_backend.service.util;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class SqlKeywords {

    public static final Set<String> RESERVED_KEYWORDS = new HashSet<>(Arrays.asList(
            "DATE", "SELECT", "FROM", "WHERE", "INSERT", "UPDATE", "DELETE", "TABLE", "JOIN", "UNION",
            "ABORT", "ABSOLUTE", "ACCESS", "ACTION", "ADD", "ADMIN", "AFTER", "AGGREGATE", "ALL", "ALSO", "ALTER",
            "ANALYSE", "ANALYZE", "AND", "ANY", "ARRAY", "AS", "ASC", "ASSERTION", "ASSIGNMENT", "ASYMMETRIC", "AT",
            "ATTACH", "ATTRIBUTE", "AUTHORIZATION", "BACKWARD", "BARRIER", "BEFORE", "BEGIN", "BETWEEN", "BIGINT", "BINARY",
            "BIT", "BLOB", "BOOLEAN", "BOTH", "BY", "CACHE", "CALL", "CASCADE", "CASE", "CAST", "CHECK", "CHECKPOINT", "CLASS",
            "CLOSE", "CLUSTER", "COALESCE", "COLLATE", "COLUMN", "COMMIT", "CONCURRENTLY", "CONFIGURATION", "CONSTRAINT",
            "CONTAINS", "CONVERT", "COPY", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP",
            "CURRENT_USER", "CURSOR", "CYCLE", "DATA", "DATABASE", "DAY", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFAULT",
            "DEFERRABLE", "DEFERRED", "DELIMITERS", "DEPENDENT", "DESC", "DISTINCT", "DO", "DOCUMENT", "DOMAIN",
            "DOUBLE", "DROP", "EACH", "ELSE", "END", "EXCEPT", "EXCLUDE", "EXCLUSIVE", "EXECUTE", "EXISTS", "EXPLAIN",
            "EXTENSION", "FALSE", "FETCH", "FOR", "FORCE", "FOREIGN", "FORWARD", "FREEZE", "FUNCTION", "GENERAL",
            "GRANT", "GROUP", "HANDLER", "HAVING", "HEADER", "HOLD", "ILIKE", "IMMEDIATE", "IMMUTABLE", "IMPLEMENTATION",
            "IN", "INCLUDING", "INCREMENT", "INDEX", "INHERIT", "INHERITS", "INITIALLY", "INNER", "INSTEAD", "INTERSECT",
            "INTERVAL", "INTO", "IS", "ISNULL", "JSON", "LATERAL", "LEADING", "LEFT", "LEVEL", "LIMIT", "LISTEN", "LOAD",
            "LOCAL", "LOCK", "LOCKED", "LOG", "MATCH", "MAXVALUE", "MINVALUE", "MODULE", "NAMES", "NATURAL", "NEXT", "NO",
            "NOCREATEDB", "NOCREATEROLE", "NOINHERIT", "NOLOGIN", "NOSUPERUSER", "NOT", "NOTHING", "NOTNULL", "NULL", "NULLIF",
            "NUMERIC", "OF", "OFF", "OFFSET", "ON", "ONLY", "OPERATOR", "ORDER", "OUT", "OUTER", "OVER", "OVERLAPS", "RECURSIVE",
            "REFERENCES", "REINDEX", "RELATIVE", "RENAME", "REPEATABLE", "REPLACE", "RESET", "RESTART", "RESTRICT", "RETURN",
            "RETURNING", "REVOKE", "RIGHT", "ROLE", "SEQUENCE", "SESSION", "SET", "SHOW", "SIMILAR", "SIMPLE", "SLOT",
            "SMALLINT", "START", "STATEMENT", "STATISTICS", "STABLE", "STANDALONE", "TABLESAMPLE", "THEN", "TO", "TRANSACTION",
            "TRIGGER", "TRUE", "UNBOUNDED", "UNIQUE", "USER", "USING", "VACUUM", "VALID", "VALUE", "VALUES", "VARIADIC",
            "VARYING", "VERBOSE", "VIEW", "VOLATILE", "WHEN", "WHERE", "WHITESPACE", "WITH", "WITHOUT", "WORK", "YEAR", "ZONE"
    ));


}
